### ISSUE TITLE
[imx8m-var-dart] Wifi fails to come back after resume from suspend

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-variscite#81]
Using an docker container like:
```
FROM balenalib/aarch64-ubuntu
RUN install_packages pm-utils
```                    
Then run `pm-suspend` and wait for the board to sleep, then bring it back up by pushing the `On/Off` button. After restarting the device the wifi chip fails as follows:

```
 [ 9872.520456] CPU3 is up
[ 9872.524392] PM: noirq resume of devices complete after 3.929 msecs
[ 9872.525802] PM: early resume of devices complete after 1.146 msecs
[ 9872.529721] Suspended for 189.255 seconds
[ 9872.591590] mmc1: error -110 during resume (card was removed?)
[ 9872.773245] usb 2-1: reset SuperSpeed USB device number 2 using xhci-hcd
[ 9873.387470] PM: resume of devices complete after 861.649 msecs
[ 9873.503405] Restarting tasks ... done.
[ 9873.514788] hantro receive hot notification event: 0
[ 9873.522314] brcmfmac: brcmf_cfg80211_reg_notifier: not a ISO3166 code (0x30 0x30)
[ 9873.611347] brcmfmac: brcmf_sdio_txfail: sdio error, abort command and terminate frame
[ 9873.620903] brcmfmac: brcmf_sdio_txfail: sdio error, abort command and terminate frame
[ 9873.630459] brcmfmac: brcmf_sdio_txfail: sdio error, abort command and terminate frame
[ 9873.638958] brcmfmac: brcmf_sdio_dpc: failed backplane access over SDIO, halting operation
[ 9873.638962] brcmfmac: brcmf_do_escan: error (-84)
[ 9873.638968] brcmfmac: brcmf_cfg80211_scan: scan error 
```

**Comment by shaunmulligan** [comment]
Similar thing happens if one uses RTCwake as described here: http://variwiki.com/index.php?title=DART-MX8M_RTC

**Comment by acostach** [comment]
It looks like the drivers do not handle the suspend states correctly and Variscite imx6, 7 and 8 handle this issue by reloading the modules with all the necessary configuration, just like when the board is powered up for the first time.

I have created https://github.com/balena-os/balena-variscite/pull/85 to add pm-utils and as well as the script to handle wifi down/up when using pm utils, just like the board vendor does. This makes wifi resume correctly when triggered from inside host-os.

However, since pm-utils is comprised of a collection of scripts and not a daemon, this means that pm-suspend and the resume hooks need to from the same filesystem. When the pm-suspend script resumes execution, after suspend, it will invoke /etc/pm/sleep.d/imx8m-wifi.sh resume, according to its' internal state. 

Therefore, if running pm-suspend from inside the container, it will be necessary to have the hooks present there, as well as all the wifi scripts from /etc/wifi. Nor pm-utils neither systemd will trigger any resume unit or script unless its' target state was set from commands within its' rootfs.

**Comment by acostach** [comment]
Steps that can be used to suspend the board from container:

# install_packages dbus
# export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
# dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true
